// template-react-js/src/options/Options.jsx
import { useState } from 'react'
import './Options.css'

function App() {
  const [crx, setCrx] = useState('create-chrome-ext')

  return (
    <main>
      <h3>Options Page!</h3>

      <h6>v 0.0.0</h6>

      <a href="https://www.npmjs.com/package/create-chrome-ext" target="_blank">
        Power by {crx}
      </a>
    </main>
  )
}

export default App

// template-qwik-js/src/options/Options.jsx
import { component$, useStore, useRef, useEffect$ } from '@builder.io/qwik'
import './Options.css'

export const Options = () => {
  const [crx, setCrx] = useState('create-chrome-ext')

  return (
    <main>
      <h3>Options Page!</h3>

      <h6>v 0.0.0</h6>

      <a href="https://www.npmjs.com/package/create-chrome-ext" target="_blank">
        Power by {crx}
      </a>
    </main>
  )
}

export default Options
