// template-react-ts/src/devtools/index.tsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import { DevTools } from './DevTools'
import './index.css'

ReactDOM.createRoot(document.getElementById('app') as HTMLElement).render(
  <React.StrictMode>
    <DevTools />
  </React.StrictMode>,
)

chrome.devtools.panels.create('ReactCrx', '', '../../devtools.html', function () {
  console.log('devtools panel create')
})

// template-solid-js/src/devtools/index.jsx
/* @refresh reload */
import { render } from 'solid-js/web'

import './index.css'
import { DevTools } from './DevTools'

render(() => <DevTools />, document.getElementById('app') ?? document.body)

chrome.devtools.panels.create('SolidCrx', '', '../../devtools.html', function () {
  console.log('devtools panel create')
})
