// template-solid-js/src/options/Options.jsx
import { createSignal, createEffect } from 'solid-js'

import './Options.css'

export const Options = () => {
  const [countSync, setCountSync] = createSignal(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  createEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCountSync(result.count || 0)
    })

    chrome.runtime.onMessage.addListener((request) => {
      if (request.type === 'COUNT') {
        setCountSync(request.count || 0)
      }
    })
  })

  return (
    <main>
      <h3>Options Page</h3>
      <h4>Count from Popup: {countSync()}</h4>
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Options

// template-inferno-js/src/options/Options.jsx
import { Component } from 'inferno'
import './Options.css'

export class Options extends Component {
  link = 'https://github.com/guocaoyi/create-chrome-ext'

  constructor(props) {
    super(props)

    this.state = {
      countSync: 0,
    }
  }

  componentDidMount() {
    chrome.storage.sync.get(['count'], (result) => {
      this.setState({ countSync: result.count || 0 })
    })

    chrome.runtime.onMessage.addListener((request) => {
      if (request.type === 'COUNT') {
        this.setState({ countSync: request.count || 0 })
      }
    })
  }

  render() {
    return (
      <main>
        <h3>Options Page</h3>
        <h4>Count from Popup: {this.state.countSync}</h4>
        <a href={this.link} target="_blank">
          generated by create-chrome-ext
        </a>
      </main>
    )
  }
}

export default Options
